version: 2
jobs:
  build:
    working_directory: ~/dorm_elect
    docker:
      - image: centos:centos7
    steps:
      - run:
          name: Update Container
          command: yum update -y
      - run:
          name: Hotfix to container
          command: yum install -y ca-certificates curl sudo
      - run:
          name: Install Required complier
          command: yum install -y uglifyjs zip unzip git epel-release
      - run:
          name: Install PHP 
          command: yum install -y php php-curl php-mbstring php-mcrypt php-xml php-ldap php-cli php-common
      - run:
          name: Check PHP version
          command: php -v
      - checkout
      - run:
          name: Install NodeJS
          command: |
            curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
            apt-get install -y nodejs
            apt-get install -y build-essential
      - run:
          name: Install composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
      - run:
          name: composer
          command: |
            php composer.phar require --dev jakub-onderka/php-parallel-lint
            php composer.phar require --dev jakub-onderka/php-console-highlighter
      - run:
          name: Test Files
          command: ./vendor/bin/parallel-lint .
      - store_artifacts:
          path: /root/dorm_elect